### ISSUE TITLE
angular solana wallet adapter update 

### ISSUE THREAD

**Issue by Amir0x1** [heavy-duty/platform#163]
### Description

I am reaching out regarding my medium-sized application, which heavily relies on your Angular Wallet Adapter. 
I would like to know if you have any upcoming plans to release a new version of the adapter that incorporates the latest updates for Angular and the original wallet adapter.

I appreciate your attention to this matter and look forward to your response.

### Proposed solution

dependency update

### Alternatives considered

dependency update

**Comment by danmt** [comment]
Hey there, we moved the wallet adapter to https://github.com/heavy-duty/wallet-adapter 

It hasn't been updated to Angular v16 yet, but it was updated not so long ago. If the problem persists, submit an issue in the other repo, I'll close this one for now.

Would you mind letting me know the name of your application? I'm always looking forward to meet angular devs in the solana eco.

**Comment by Amir0x1** [comment]
that's amazing!
here's my app:
https://compact-defi.xyz/

you can find me on twitter: @Avaulto

**Comment by danmt** [comment]
Just gave ya a follow, feel free to submit issues in the other repo. We've been working hard to improve the dev experience, lmk if you have suggestions on how to make it better for all.
