### ISSUE TITLE
Error in instruction handler code when chars are greater than 995.

### ISSUE THREAD

**Issue by andresmgsl** [heavy-duty/platform#87]
In the instruction handler's code editor, when code exceed 995 length chars, it fails when saving.

![Screenshot from 2021-12-24 17-15-44](https://user-images.githubusercontent.com/6069831/147366114-f602c9c6-0440-425a-9658-7127de32f702.png)
![Screenshot from 2021-12-24 17-54-56](https://user-images.githubusercontent.com/6069831/147366117-244f7621-6f43-4269-a512-95213f881d85.png)

**Comment by danmt** [comment]
This issue apparently is due to the size of the transaction, we have to divide the transaction in chunks and send multiple transactions when the code is longer than 995.
