### ISSUE TITLE
Anchor Support?

### ISSUE THREAD

**Issue by rmdorsey** [heavy-duty/platform#99]
Hi, is there an anchor compatible wallet somewhere in your library that I'm missing?  I saw this, but it's for the react library: https://github.com/solana-labs/wallet-adapter/blob/master/packages/core/react/src/useAnchorWallet.ts

Thank you!

**Comment by rmdorsey** [comment]
n/m i found it.

**Comment by danmt** [comment]
Glad you figured it out!

Were you able to solve the other problem you had? One of our team members was trying to understand what was going on.
